/* This file is auto-generated using the IRQN tool. Do not modify. */

#ifndef IRQN_HANDLER

#include <stm32f0xx_it.h>

#else

IRQN_HANDLER(-14, NonMaskableInt)
IRQN_HANDLER(-13, HardFault)
SKIP_HANDLER(-12)
SKIP_HANDLER(-11)
SKIP_HANDLER(-10)
SKIP_HANDLER(-9)
SKIP_HANDLER(-8)
SKIP_HANDLER(-7)
SKIP_HANDLER(-6)
IRQN_HANDLER(-5, SVC)
SKIP_HANDLER(-4)
SKIP_HANDLER(-3)
IRQN_HANDLER(-2, PendSV)
IRQN_HANDLER(-1, SysTick)
IRQN_HANDLER(0, WWDG)
IRQN_HANDLER(1, VDDIO2)
IRQN_HANDLER(2, RTC)
IRQN_HANDLER(3, FLASH)
IRQN_HANDLER(4, RCC_CRS)
IRQN_HANDLER(5, EXTI0_1)
IRQN_HANDLER(6, EXTI2_3)
IRQN_HANDLER(7, EXTI4_15)
IRQN_HANDLER(8, TSC)
IRQN_HANDLER(9, DMA1_Channel1)
IRQN_HANDLER(10, DMA1_Channel2_3)
IRQN_HANDLER(11, DMA1_Channel4_5)
IRQN_HANDLER(12, ADC1)
IRQN_HANDLER(13, TIM1_BRK_UP_TRG_COM)
IRQN_HANDLER(14, TIM1_CC)
IRQN_HANDLER(15, TIM2)
IRQN_HANDLER(16, TIM3)
SKIP_HANDLER(17)
SKIP_HANDLER(18)
IRQN_HANDLER(19, TIM14)
SKIP_HANDLER(20)
IRQN_HANDLER(21, TIM16)
IRQN_HANDLER(22, TIM17)
IRQN_HANDLER(23, I2C1)
SKIP_HANDLER(24)
IRQN_HANDLER(25, SPI1)
IRQN_HANDLER(26, SPI2)
IRQN_HANDLER(27, USART1)
IRQN_HANDLER(28, USART2)
SKIP_HANDLER(29)
IRQN_HANDLER(30, CEC_CAN)
IRQN_HANDLER(31, USB)

#endif

